version: "3.7"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.15.1"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
